{"timestamp": "2025-02-07T20:39:39.844209", "input": {"text": "What is unusual about this image?", "image_path": "examples/extreme_ironing.jpg", "model": "llava-v1.5-13b", "temperature": 0.2, "top_p": 0.7, "max_new_tokens": 512}, "response": "HTTPConnectionPool(host='localhost', port=21001): Max retries exceeded with url: /get_worker_address (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75ee63f6f3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))", "model": "llava-v1.5-13b", "processing_time": 0.0041506290435791016, "status": "error"}
{"timestamp": "2025-02-07T20:39:39.847047", "input": {"text": "What is unusual about this image?", "image_path": "examples/extreme_ironing.jpg", "model": "llava-v1.5-13b", "temperature": 0.2, "top_p": 0.7, "max_new_tokens": 512}, "response": "HTTPConnectionPool(host='localhost', port=21001): Max retries exceeded with url: /get_worker_address (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75ee63fde090>: Failed to establish a new connection: [Errno 111] Connection refused'))", "model": "llava-v1.5-13b", "processing_time": 0.0016851425170898438, "status": "error"}
{"timestamp": "2025-02-07T20:39:39.849423", "input": {"text": "What should I be cautious about here?", "image_path": "examples/waterview.jpg", "model": "llava-v1.5-13b", "temperature": 0.2, "top_p": 0.7, "max_new_tokens": 512}, "response": "HTTPConnectionPool(host='localhost', port=21001): Max retries exceeded with url: /get_worker_address (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75ee63faa490>: Failed to establish a new connection: [Errno 111] Connection refused'))", "model": "llava-v1.5-13b", "processing_time": 0.0016362667083740234, "status": "error"}
{"timestamp": "2025-02-07T20:43:41.599449", "input": {"text": "What is unusual about this image?", "image_path": "./images/slo_fundus_00001.jpg", "model": "llava-v1.5-13b", "temperature": 0.2, "top_p": 0.7, "max_new_tokens": 512}, "response": "HTTPConnectionPool(host='10.105.10.32', port=21001): Max retries exceeded with url: /get_worker_address (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75ee62b24e10>: Failed to establish a new connection: [Errno 111] Connection refused'))", "model": "llava-v1.5-13b", "processing_time": 0.0030074119567871094, "status": "error"}
{"timestamp": "2025-02-07T20:45:52.686890", "input": {"text": "What is unusual about this image?", "image_path": "./images/slo_fundus_00001.jpg", "model": "llava-v1.5-13b", "temperature": 0.2, "top_p": 0.7, "max_new_tokens": 512}, "response": "No available worker", "model": "llava-v1.5-13b", "processing_time": 0.005468606948852539, "status": "error"}
{"timestamp": "2025-02-07T20:49:37.944359", "input": {"text": "What is unusual about this image?", "image_path": "./images/slo_fundus_00001.jpg", "model": "llava-v1.5-13b", "temperature": 0.2, "top_p": 0.7, "max_new_tokens": 512}, "response": "No available worker", "model": "llava-v1.5-13b", "processing_time": 0.005797863006591797, "status": "error"}
{"timestamp": "2025-02-07T20:49:59.714017", "input": {"text": "What is unusual about this image?", "image_path": "./images/slo_fundus_00001.jpg", "model": "llava-v1.5-13b", "temperature": 0.2, "top_p": 0.7, "max_new_tokens": 512}, "response": "No available worker", "model": "llava-v1.5-13b", "processing_time": 0.007598400115966797, "status": "error"}
{"timestamp": "2025-02-07T20:50:55.127580", "input": {"text": "What is unusual about this image?", "image_path": "./images/slo_fundus_00001.jpg", "model": "llava-v1.5-13b", "temperature": 0.2, "top_p": 0.7, "max_new_tokens": 512}, "response": "Object of type bytes is not JSON serializable", "model": "llava-v1.5-13b", "processing_time": 0.043962955474853516, "status": "error"}
{"timestamp": "2025-02-07T20:52:31.695738", "input": {"text": "What is unusual about this image?", "image_path": "./images/slo_fundus_00001.jpg", "model": "llava-v1.5-13b", "temperature": 0.2, "top_p": 0.7, "max_new_tokens": 512}, "response": "Request failed with status 404", "model": "llava-v1.5-13b", "processing_time": 0.010991811752319336, "status": "error"}
